driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-27
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: sles-11-sp2
    driver:
      box: chef/sles-11-sp2-x86_64 # private box
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64 # private box
  - name: solaris-11.3
    driver:
      box: chef/solaris-11.3 # private box

suites:
  - name: default
    run_list: test::default
  - name: create
    run_list: test::create
    excludes: ["freebsd-10", "freebsd-11"]
  - name: remove
    run_list: test::remove
    excludes: ["freebsd-10", "freebsd-11"]
