AllCops:
  Excludes:
    - vendor/**

AlignParameters:
  Enabled: false
CyclomaticComplexity:
  Max: 10
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 40
